# -*- coding: utf-8 -*-
"""
/***************************************************************************
 LineComparison
                                 A QGIS plugin
 This plugin supports line-based accuracy assessment by comparing two line layers. Both layers are first buffered, then rasterized and overlaid to compute the confusion matrix. The confusion matrix is saved as a text file containing the errors of omission and commission. 
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2018-08-01
        copyright            : (C) 2018 by Sophie Crommelinck
        email                : s.crommelinck@utwente.nl
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load LineComparison class from file LineComparison.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .LineComparison import LineComparison
    return LineComparison(iface)
